/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.gitter.app;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("My Git PullRequest");
        System.out.println("My Git PullRequest2");
    }
}
